# Deeplearning for computer vision

## Tensors:

Tensors are multi deimetional arrays. The array is an ordered arrangement of numbers.

For example,

[8] -> 0 Dimentional tensors

[1,3,4] -> 1 Dimentional tensors

[[1,3,4],
[2,4,5]] -> 2 Dimentional tensors

Serval 2D tensors combine to form 3D tensors and so on.

Probablity distribution reference:
https://www.acsu.buffalo.edu/~adamcunn/probability/probability.html

In [1]:
import tensorflow as tf

In [2]:
# create tensor
tensor_0_d = tf.constant(1)
print(tensor_0_d)

tf.Tensor(1, shape=(), dtype=int32)


In [3]:
tensor_1_d = tf.constant([2,4,5,6,5])
print(tensor_1_d)

tf.Tensor([2 4 5 6 5], shape=(5,), dtype=int32)


In [15]:
tf.constant([2,4,5,6,5],dtype=tf.float16) # 16, 32, 64 will denotes how much memory allocate to the tensor

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([2., 4., 5., 6., 5.], dtype=float16)>

In [18]:
# To convert float tensor to int tensor or other conversion we can use tf.cast. If we try to assign directly datatype as int for convert float tensor to int, this leads to error.
float_tensor = tf.constant([2,4.3,6.5,6,5],dtype=tf.float16)
int_tensor = tf.cast(float_tensor, dtype=tf.int16)
int_tensor

<tf.Tensor: shape=(5,), dtype=int16, numpy=array([2, 4, 6, 6, 5], dtype=int16)>

In [19]:
tf.cast(float_tensor, dtype=tf.bool)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [20]:
tf.constant(['hi','hello'])

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hi', b'hello'], dtype=object)>

In [5]:
tensor_2_d = tf.constant([
    [2,4,5,6,5],
    [2,4,5,6,5],
    [2,4,5,6,5]
])
print(tensor_2_d)

tf.Tensor(
[[2 4 5 6 5]
 [2 4 5 6 5]
 [2 4 5 6 5]], shape=(3, 5), dtype=int32)


In [7]:
tensor_3_d = tf.constant([
    [[2, 4 ,5 ,6, 5],
     [2, 4, 5, 6, 5],
     [2, 4, 5, 6, 5]],
    [[2, 4, 5,6, 5],
     [2, 4, 5, 6, 5],
     [2, 4, 5, 6, 5]]
])
print(tensor_3_d)

tf.Tensor(
[[[2 4 5 6 5]
  [2 4 5 6 5]
  [2 4 5 6 5]]

 [[2 4 5 6 5]
  [2 4 5 6 5]
  [2 4 5 6 5]]], shape=(2, 3, 5), dtype=int32)


In [10]:
# get tensor shape
tensor_3_d.shape

TensorShape([2, 3, 5])

In [11]:
# get tensor dimention
tensor_3_d.ndim

3

Stacking a several 3-D tensor will form a 4-D tensor

In [12]:
tensor_4_d = tf.constant([
    [
    [[2, 4 ,5 ,6, 5],
     [2, 4, 5, 6, 5],
     [2, 4, 5, 6, 5]],
    [[2, 4, 5,6, 5],
     [2, 4, 5, 6, 5],
     [2, 4, 5, 6, 5]]
],
    [
    [[2, 4 ,5 ,6, 5],
     [2, 4, 5, 6, 5],
     [2, 4, 5, 6, 5]],
    [[2, 4, 5,6, 5],
     [2, 4, 5, 6, 5],
     [2, 4, 5, 6, 5]]
]
])
print(tensor_4_d)

tf.Tensor(
[[[[2 4 5 6 5]
   [2 4 5 6 5]
   [2 4 5 6 5]]

  [[2 4 5 6 5]
   [2 4 5 6 5]
   [2 4 5 6 5]]]


 [[[2 4 5 6 5]
   [2 4 5 6 5]
   [2 4 5 6 5]]

  [[2 4 5 6 5]
   [2 4 5 6 5]
   [2 4 5 6 5]]]], shape=(2, 2, 3, 5), dtype=int32)


In [21]:
# convert numpy array to tensor
import numpy as np
array = np.array([1,3,4])

In [22]:
array

array([1, 3, 4])

In [23]:
tf.convert_to_tensor(array)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 4])>

In [26]:
# Create identity matrix
eye_tensor = tf.eye(num_rows=3)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [27]:
eye_tensor * 3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]], dtype=float32)>

In [28]:
tf.eye(num_rows=3, dtype=tf.bool)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])>

In [30]:
tf.eye(num_rows=5,num_columns=3, dtype=tf.int16)

<tf.Tensor: shape=(5, 3), dtype=int16, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)>

In [31]:
tf.eye(num_rows=5,batch_shape=[3,], dtype=tf.int16)

<tf.Tensor: shape=(3, 5, 5), dtype=int16, numpy=
array([[[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]]], dtype=int16)>

In [32]:
## Fill method
    
tf.fill([2,4,5], 6, name=None)

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]],

       [[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]]])>

In [33]:
tf.ones([5,3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [36]:
array = np.array([[1,3,0],[2,5,7]])
tf.ones_like(array) # convert all tensor elements into 1's

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [37]:
tf.zeros([5,3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [38]:
tf.zeros_like(array) # convert all tensor elements into 0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [39]:
tf.rank(tf.constant(array)) # gives dimentional rank

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [40]:
tf.size(tensor_2_d) # Give number of element in tensor

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [41]:
# Generate random tensor with normal distribution

# if higher the standard deviation, width of bellcurve will increase. If higher the width, The probablity of choosing value near to mean is less

tf.random.normal([3,2], mean=100, stddev= 1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[101.611046, 100.82534 ],
       [ 99.889626, 101.26866 ],
       [101.30459 ,  99.742905]], dtype=float32)>

In [42]:
tf.random.normal([3,2], mean=100, stddev= 10) # from this we can able to understand the difference

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 93.857994, 120.64225 ],
       [107.37154 , 104.55953 ],
       [ 93.69317 , 103.54062 ]], dtype=float32)>

In [43]:
# Genrate random tensor with uniform distribution
tf.random.uniform([3,2], minval= 0, maxval=100)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[69.577385, 64.962494],
       [39.479973, 12.176776],
       [69.11316 , 25.468863]], dtype=float32)>

In [46]:
random_tensor = tf.random.uniform([3,2], minval= 0, maxval=100, dtype=tf.int32)
print(random_tensor)

tf.Tensor(
[[31 31]
 [31 14]
 [26 13]], shape=(3, 2), dtype=int32)


In [48]:
random_tensor.numpy()

array([[31, 31],
       [31, 14],
       [26, 13]])